### ISSUE TITLE
auth folder

### ISSUE THREAD

**Issue by bssher** [salihkiraz/osticket-auth-saml#1]
Thanks for updating the project. I installed the plugin, but I'm missing api/auth/saml in the api folder. Thoughts?

**Comment by salihkiraz** [comment]
try againg osticket cache clear.

**Comment by KroonCo** [comment]
Hello and thank you so much for your work on the osticket saml connection. We where waiting for this functionality for a long time. As @bssher described in a earlier message, we experience the same. Authentication results in a callback/redirect from the IDP to page-url/api/auth/saml which does not exist. Apache2 log: "POST /api/auth/saml HTTP/1.1" 404. Help on this subject will be greatly appriciated. regards

**Comment by Macel** [comment]
Hi, the original poster closed this issue but I am having the same problem and I do not see a resolution on this.  Can this be looked into further?
