### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by thenatlgbt** [salihkiraz/osticket-auth-saml#11]
Hello,

Is this plugin capable with Okta?

I need help setting this up

I am setting up an app in my Okta platform, it is asking for the Single Sign On URL, Audience URI.

**Comment by thenatlgbt** [comment]
Any update on this?

**Comment by salihkiraz** [comment]
Hello, the plugin is based on onelogin saml2. Please check your issue at the address below.

https://github.com/onelogin/php-saml/issues
