### ISSUE TITLE
Execution error in signOn

### ISSUE THREAD

**Issue by PaulBol** [salihkiraz/osticket-auth-saml#14]
For me `signOn` would not execute with PHP 8.0. I figured out the problem was related to the line

```php
if (method_exists(StaffSession, 'lookup')) {
```

which works when written as

```php
if (method_exists('StaffSession', 'lookup')) {
```

According to https://www.php.net/manual/en/function.method-exists.php `method_exists`  `object_or_class` must be *An object instance or a class name*.

**Comment by salihkiraz** [comment]
Can you please pull request. Test it and make sure it works.

**Comment by PaulBol** [comment]
Here you go -> #16

**Comment by PaulBol** [comment]
What will happen to the pull request?

**Comment by salihkiraz** [comment]
sorry i forgot to merge. I published it with v.13 version. Thanks for your contributions.

**Comment by PaulBol** [comment]
Thanks for the quick response @salihkiraz. I'm also planning to look into #15 but it's a bit more complex and I don't have a ton of experience with PHP.
