### ISSUE TITLE
Login does not work with Azure AD

### ISSUE THREAD

**Issue by PaulBol** [salihkiraz/osticket-auth-saml#15]
I got it to work with a few changes

In SamlStaffAuthenticationBackend.class.php add

```php
            'security' => array(
                'requestedAuthnContext' => false,
            )
```

to 

`$settings` in `getSamlConfiguration`.

Also add

```php
$_SESSION['saml']['email'] = $response->getAttributes()['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'][0];
```

where the SAML attributes are read.

And in `signOn` change

```php
        if (isset($_SESSION['saml']['nameId'])) {
            $staff_id = StaffSession::getIdByEmail($_SESSION['saml']['nameId']);
```

to

```php
        if (isset($_SESSION['saml']['email'])) {
            $staff_id = StaffSession::getIdByEmail($_SESSION['saml']['email']);
```

Ideally, the email claim name should be added to the configuration instead of being hard-coded. It also makes sense to extend the length of the fields `attribute_mapping_name` and `attribute_mapping_surname`. The value *http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname*  doesn't currently fit into the available 60 characters.

**Comment by salihkiraz** [comment]
Can you please pull request. Test it and make sure it works.
