### ISSUE TITLE
Redirect from IDP not working

### ISSUE THREAD

**Issue by KroonCo** [salihkiraz/osticket-auth-saml#2]
Hello and thank you so much for your work on the osticket saml connection. We where waiting for this functionality for a long time. As @bssher described in a earlier message, we experience the same. Authentication results in a callback/redirect from the IDP to page-url/api/auth/saml which does not exist. Apache2 log: "POST /api/auth/saml HTTP/1.1" 404. Help on this subject will be greatly appriciated. regards

**Comment by salihkiraz** [comment]
Plase check  plugins config. Idp adres https trying.

**Comment by KroonCo** [comment]
Could you be more specific? The plugin config, does it need to point to another location?

**Comment by salihkiraz** [comment]
Yout osTciket url : https://app.example.com

Saml site url : https://sso.example.com ( I used https://simplesamlphp.org/)

**!! url https !!**


Example setting:

Login Page Button Name :

Saml

Identity Provider Entity ID:

https://sso.example.com/saml2/idp/metadata.php

Identity Provider X509 Cert:

4EdjCCAt4CCQDTEiMCAOgINfEsJqKyvgDy........

Identity Provider SSO URL:

https://sso.example.com/saml2/idp/SSOService.php

Service Provider Entity ID:

https://app.example.com

Assertion Consumer Service URL:

https://app.example.com/api/auth/saml

Attribute Mapping

Attribute Mapping Options

Name:

givenName

Surname:

sn

Authentication Modes

Staff Authentication:

Enable authentication of staff members

Client Authentication:

Enable authentication and discovery of clients

**Comment by KroonCo** [comment]
Hello,

Yes I understand the configuration, but on the OSTicket side the whole https://app.example.com/api/auth/saml   url is missing. No folders corresponding to the URL are on the backend.

Should the plugin create the /api/auth/saml?
Thanks,

Jack de Jong


Energieweg 53a
Technisch Consultant
2382 ND Zoeterwoude
[Afbeelding met object  Automatisch gegenereerde beschrijving]
T (088) 006 4900
W www.kroonco.nl<http://www.kroonco.nl/>


Van: Salih KİRAZ <notifications@github.com>
Verzonden: Tuesday, 19 May 2020 01:37
Aan: salihkiraz/osticket-auth-saml <osticket-auth-saml@noreply.github.com>
CC: Support | KroonCo <support@kroonco.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [salihkiraz/osticket-auth-saml] Redirect from IDP not working (#2)


Yout osTciket url : https://app.example.com

Saml site url : http://sso.example.com ( I used https://simplesamlphp.org/)

Example setting:

Login Page Button Name :

Saml

Identity Provider Entity ID:

https://sso.example.com/saml2/idp/metadata.php

Identity Provider X509 Cert:

4EdjCCAt4CCQDTEiMCAOgINfEsJqKyvgDy........

Identity Provider SSO URL:

https://sso.example.com/saml2/idp/SSOService.php

Service Provider Entity ID:

https://app.example.com

Assertion Consumer Service URL:

https://app.example.com/api/auth/saml

Attribute Mapping

Attribute Mapping Options

Name:

givenName

Surname:

sn

Authentication Modes

Staff Authentication:

Enable authentication of staff members

Client Authentication:

Enable authentication and discovery of clients

**Comment by salihkiraz** [comment]
It doesn't have to be a folder. Url error is generally valid because there is something wrong with your settings.

Please download the new version and try to solve your error by activating the debug mode from the settings.

https://github.com/salihkiraz/osticket-auth-saml/releases/tag/v1.1

**Comment by callum-p** [comment]
I'm having this issue too. Here are my settings:

![image](https://user-images.githubusercontent.com/7827942/116504619-d00ac300-a90c-11eb-92cd-051533000bf9.png)

**Comment by callum-p** [comment]
Solved this this morning. It was an issue with my apache configuration. Had to run `a2enmod rewrite` inside the dockerfile.

**Comment by salihkiraz** [comment]
Thanks for sharing the solution.
