### ISSUE TITLE
Signature validation failed. SAML Response rejected

### ISSUE THREAD

**Issue by lafonso** [salihkiraz/osticket-auth-saml#3]
Thank you so much for your work, hope you are gong well.
I try to configure saml login on a Google Gsuite account, but no mater what config i use always the same behavior.
Click login, it send me to google login, made login it redirect me to osticket where i receive "Signature validation failed. SAML Response rejected" 
Any hint ? already read your example configuration a lot but have no idea where is my fault

**Comment by salihkiraz** [comment]
It can usually be a url error. Can you share your configuration.

**Comment by lafonso** [comment]
Atached you can see all my configuration page, i just remove my domain in URL
![Image 13](https://user-images.githubusercontent.com/1064993/86021064-0fbc0200-b9ff-11ea-8660-4d19bc543bad.png)

**Comment by salihkiraz** [comment]
hi, 

try


Service Provider Entty ID : https://accounts.google.com/o/saml2?idpid=C039I4n0b

**Comment by lafonso** [comment]
I change service as you say but i receive another error now, after login on google with a domain account i get a 403 error
app_not_cofigured_for_user
So i tryed with the other param "https://accounts.google.com/o/saml2/idp?idpid=C039l4n0b" but same errror

![Image 14](https://user-images.githubusercontent.com/1064993/86123694-53227900-bab0-11ea-8554-ab8d3d377881.png)

Bellow is my config on gsuite
![Image 15](https://user-images.githubusercontent.com/1064993/86124766-03dd4800-bab2-11ea-9473-4379f3789525.png)
![Image 16](https://user-images.githubusercontent.com/1064993/86124787-0b045600-bab2-11ea-812a-8e9393f60d64.png)

**Comment by salihkiraz** [comment]
this plugin php-saml based . 

see

https://github.com/onelogin/php-saml/issues?q=is%3Aissue+google+is%3Aclosed
