### ISSUE TITLE
Error "Signature validation failed. SAML Response rejected"

### ISSUE THREAD

**Issue by benmo** [salihkiraz/osticket-auth-saml#4]
Hi there,

Thank you very much for this awesome plugin.

I tried to use Azure AD, but I get an error: Signature validation failed. SAML Response rejected. Just like #3 

Here is my configuration:
![image](https://user-images.githubusercontent.com/69507095/94183820-4ccf4d80-fea3-11ea-87b0-9c3f81a0872b.png)

And this is my config on Azure AD:
![image](https://user-images.githubusercontent.com/69507095/94183969-8b650800-fea3-11ea-8bb5-b12049c1d125.png)
![image](https://user-images.githubusercontent.com/69507095/94183911-74beb100-fea3-11ea-8d91-a6f5152a7002.png)
![image](https://user-images.githubusercontent.com/69507095/94184051-a46db900-fea3-11ea-84be-9b8d6c9f6fe9.png)

I tried everything, but I just can't find the error. Can you help me?

**Comment by benmo** [comment]
The SAML response appears to be vaild too, according to samltool.org:
![image](https://user-images.githubusercontent.com/69507095/94187402-31b30c80-fea8-11ea-9738-eaee67a05bc6.png)

**Comment by salihkiraz** [comment]
Sorry I don't have the data to test this. You can review the link below.

https://tsmatz.wordpress.com/2016/12/29/azure-ad-saml-federation-application-tutorial/

You can also check the details at https://github.com/onelogin/php-saml.

**Comment by benmo** [comment]
I was able to debug and fix the error by modifying `lib/Saml2/Response.php` on line 387, the fingerprint of the x509cert.
Instead of `$fingerprint = $idpData['certFingerprint'];`, I assigned the fingerprint to the variable as a string. I don't know if that's a bug with the tool. Where does he normally get the fingerprint from?

**Comment by semil19** [comment]
Hi @benmo can you help me this, new to os ticket currently running version 1.15.1.
Where to place these files and how to configure ?

Thanx in Advance
