### ISSUE TITLE
It's not working for me. Would you help me?

### ISSUE THREAD

**Issue by paulobarbassa** [salihkiraz/osticket-auth-saml#6]
I did all the configuration as per your example, but although the authentication happens correctly, it remains on the OsTicket login page.

We are using Azure AD.

![image](https://user-images.githubusercontent.com/16267426/125094226-76134000-e0a9-11eb-89f8-e100970d5ad0.png)

**Comment by salihkiraz** [comment]
Hello, do you have something similar to the error you are getting?

**Comment by paulobarbassa** [comment]
Only message: "Have your administrator create a local account"

![image](https://user-images.githubusercontent.com/16267426/126396513-97df8717-da70-434a-8be1-3011972f23b0.png)


![20210720_181409](https://user-images.githubusercontent.com/16267426/126396461-3c847b48-f456-4fa3-bff6-f1b67cd89349.gif)

**Comment by fenichelar** [comment]
I had the same issue. Azure returned the `nameId` attribute in transient format as requested but this plugin appears to expect emailAddress format.

Change `urn:oasis:names:tc:SAML:2.0:nameid-format:transient` to `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress` on these two lines:

https://github.com/salihkiraz/osticket-auth-saml/blob/master/SamlStaffAuthenticationBackend.class.php#L70
https://github.com/salihkiraz/osticket-auth-saml/blob/master/SamlStaffAuthenticationBackend.class.php#L186

**Comment by paulobarbassa** [comment]
Thank you @fenichelar!
Worked perfectly!
