### ISSUE TITLE
Setup Clarification/Documentation

### ISSUE THREAD

**Issue by Macel** [salihkiraz/osticket-auth-saml#9]
Some better documentation on how to set this up would be extremely helpful.  The readme implies some settings but it needs to be more clear.

For a given osTicket installation (https://myOSTicket.mydomain.com), what should the ACS URL be? 

What should the entity ID be?

Should we expect the physical path on the web server to actually contain /api/auth/saml ? Or is that a virtual path created by the plugin?  In troubleshooting I am looking for that physical path but do not see it there.

What exactly is debug mode and how do we use it for troubleshooting?

**Comment by thenatlgbt** [comment]
I would like something as well. Is this plugin capable with Okta?

I need help setting this up

**Comment by salihkiraz** [comment]
Hello, the plugin is based on onelogin saml2. Please check your issue at the address below.

https://github.com/onelogin/php-saml/issues
